### ISSUE TITLE
Adding Discord link

### ISSUE THREAD

**Issue by Matavatar** [p0lygun/deep_worlds_studio#1]
Adding Discord button:
![image](https://user-images.githubusercontent.com/65628145/231490371-6ab56d07-883d-46c0-96fb-6fed9600cb86.png)

Adding Discord link in footer:
![image](https://user-images.githubusercontent.com/65628145/231491703-1fc28470-70b9-4310-8dbb-b5a1ef02a4e7.png)

**Comment by p0lygun** [comment]
will do
